### ISSUE TITLE
can i connect to ws://socketserver ?

### ISSUE THREAD

**Issue by ramstein74** [joncursi/socket-io-client#3]
hello iḿ trying but cannot connect to my server

I have a normal webpage that connects like this

web2py_websocket('ws://serverip:12200/realtime/mygroup1')

trying to connect using your package does not do anything

this is my code using your package to mimic my previous code...
var socket = io('ws://serveip:12200/realtime/');

// subscribe to a data feed
socket.emit('subscribe', 'mygroup1');

are they equivalent ?

should i replace ws with http?

regards

**Comment by joncursi** [comment]
Hey. A couple of things:
1. `var socket = io('ws://serveip:12200/realtime/');` --> `serveip` should be replaced with the server's actual IP address, but I assume you already know this. Also, use the full URL (include `/mygroup1`).
2. I can't tell what data feeds your server is publishing, and whether or not you need `socket.emit( ... );`. Try jumping straight to `socket.on('connect', ... );` to see if you can connect to the webserver.
3. This is just a Meteor wrapper for the NPM package. Check here for more official documentation and support, check out https://www.npmjs.com/package/socket.io-client
