### ISSUE TITLE
Web socket connection not receiving data after re-connect

### ISSUE THREAD

**Issue by weijian19391** [joncursi/socket-io-client#5]
Hi! 

I have the following issue that i have resolved, but still would like to put it here for 2 reasons:
1. I would like to know if this is a bug or it's supposed to work like this.
2. To help anyone who chance upon this problem in future.
### Problem:

```
getSensorDataWebSoc: function(deviceModel,deviceUUId,deviceSensors) {
        if(!socket){
            socket = io('https://websocket.btcchina.com/');
            socket.emit('subscribe', 'marketdata_cnybtc');
            socket.on('connect', Meteor.bindEnvironment(function() {
                socket.on('trade', Meteor.bindEnvironment(function(data) {
                   console.log(data);
                  }, function(e) {
                    throw e;
                  }));
                  socket.on('disconnect', Meteor.bindEnvironment(function() {
                    console.log('Disconnected from the websocket!');
                  }, function(e) {
                    console.log("in disconnect fail " + e);
                    throw e;
                  }));
                }, function(e) {
              console.log("inside connection fail");
                  throw e;
                }));
        } else {
            console.log("socket existed");
            socket.connect();
        }   
 },
closeWebSoc: function(){
    socket.disconnect(true);
},
```

I have the above code placed inside `Meteor.methods`. It's a very standard web socket connection, and i'm listening on the `trade` event. What i realised is that once i called the closeWebSoc function when i leave a template, and re-enter the template again, i won't be receiving any data anymore. The same result applies even after i refresh the page, close the browser and re-open the meteor app. The only 'fix' to get back my connection with data streaming in is to restart the meteor app. 

After hours of debugging, i realised that the problems comes from `socket.emit`. Apparently, after reconnecting, the `socket` object does not contain the object holding those variables (as seen from `socket.sendBuffer[0].data`). 
### Solution:

To solve that issue is actually quite simple: we simply re-emit the subscribe again before we run the connect: 

```
getSensorDataWebSoc: function(deviceModel,deviceUUId,deviceSensors) {
        if(!socket){
            socket = io('https://websocket.btcchina.com/');
            socket.emit('subscribe', 'marketdata_cnybtc');
            socket.on('connect', Meteor.bindEnvironment(function() {
                socket.on('trade', Meteor.bindEnvironment(function(data) {
                   console.log(data);
                  }, function(e) {
                    throw e;
                  }));
                  socket.on('disconnect', Meteor.bindEnvironment(function() {
                    console.log('Disconnected from the websocket!');
                  }, function(e) {
                    console.log("in disconnect fail " + e);
                    throw e;
                  }));
                }, function(e) {
              console.log("inside connection fail");
                  throw e;
                }));
        } else {
            console.log("socket existed");
            socket.emit('subscribe', 'marketdata_cnybtc');//new line added to make it work.
            socket.connect();
        }   
 },
closeWebSoc: function(){
    socket.disconnect(true);
},
```

and viola! Now the connection works as expected. 

Any idea if this is the intended work flow to use or is this a bug of the code? 
Thank you!

**Comment by joncursi** [comment]
I'm not sure if this is the preferred solution or if a better alternative exists, but thank you for posting your work-around!
